default:
	gcc -o simple simple.c
	gcc -o num num.c
	gcc -o compute_address compute_address.c
	gcc -o struct_test struct_test.c
	gcc -o negation negation.c
	gcc -o func_call func_call.c
	gcc -o big_if_else big_if_else.c
	gcc -o array_loop array_loop.c
clean:
	rm simple num compute_address struct_test negation func_call big_if_else array_loop
