default:
	gcc -o simple simple.c
	gcc -o num num.c
	gcc -o compute_address compute_address.c
	gcc -o struct_test struct_test.c
	gcc -o negation negation.c
clean:
	rm simple num compute_address struct_test negation
