ln -sf /lib/libQt6Core.so.6.7.2 /opt/binaryninja/libQt6Core.so.6
ln -sf /lib/libQt6DBus.so.6.7.2 /opt/binaryninja/libQt6DBus.so.6
ln -sf /lib/libQt6Gui.so.6.7.2 /opt/binaryninja/libQt6Gui.so.6
ln -sf /lib/libQt6Network.so.6.7.2 /opt/binaryninja/libQt6Network.so.6
ln -sf /lib/libQt6Widgets.so.6.7.2 /opt/binaryninja/libQt6Widgets.so.6
ln -sf /lib/libQt6XcbQpa.so.6.7.2 /opt/binaryninja/libQt6XcbQpa.so.6
#ln -sf /lib/libicui18n.so.72 /opt/binaryninja/libicui18n.so.72
#ln -sf /lib/libicu18n.so.72 /opt/binaryninja/libicu18n.so.72
#ln -sf /lib/libicuuc.so.72 /opt/binaryninja/libicuuc.so.72
