ln -sf $(pwd)/qt-libs/libQt6Core.so.6.7.2 /opt/binaryninja/libQt6Core.so.6
ln -sf $(pwd)/qt-libs/libQt6DBus.so.6.7.2 /opt/binaryninja/libQt6DBus.so.6
ln -sf $(pwd)/qt-libs/libQt6Gui.so.6.7.2 /opt/binaryninja/libQt6Gui.so.6
ln -sf $(pwd)/qt-libs/libQt6Network.so.6.7.2 /opt/binaryninja/libQt6Network.so.6
ln -sf $(pwd)/qt-libs/libQt6Widgets.so.6.7.2 /opt/binaryninja/libQt6Widgets.so.6
ln -sf $(pwd)/qt-libs/libQt6XcbQpa.so.6.7.2 /opt/binaryninja/libQt6XcbQpa.so.6
ln -sf $(pwd)/qt-libs/libicui18n.so.72 /opt/binaryninja/libicui18n.so.72
ln -sf $(pwd)/qt-libs/libicu18n.so.72 /opt/binaryninja/libicu18n.so.72
ln -sf $(pwd)/qt-libs/libicuuc.so.72 /opt/binaryninja/libicuuc.so.72
